{% set name = "openptv" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  # Uncomment the following line if the package is pure Python and the recipe
  # is exactly the same for all platforms. It is okay if the dependencies are
  # not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python
  # for more details.
  # noarch: python

  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

  # If the installation is complex, or different between Unix and Windows,
  # use separate bld.bat and build.sh files instead of this key. By default,
  # the package will be built for the Python versions supported by conda-forge
  # and for all major OSs. Add the line "skip: True  # [py<35]" (for example)
  # to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit
  # to Windows.
  script:
    - cd py_bind
    - {{ PYTHON }} setup.py prepare
    - {{ PYTHON }} setup.py install
  # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - cython
    - pyyaml
    - six
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pyyaml

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  source_files:
    - py_bind/test
  requires:
    - nose
  commands: 
    - cd py_bind/test
    - nosetests 
  imports:
    - optv

# Uncomment and fill in openptv metadata
about:
 home: https://github.com/openptv
 license: LGPL-3.0
 license_family: GPL
 license_file: COPYING.LESSER

# Uncomment the following if this will be on a forge
# Remove these lines if this is only be used for CI
extra:
 recipe-maintainers:
   - alexlib
