[build-system]
requires = ["numpy", "cython", "setuptools", "wheel", "cibuildwheel"]
build-backend = "setuptools.build_meta"
# py_modules = ["optv"]
# where = ["."]
# include = ["liboptv","py_bind"]

[tool.cibuildwheel]
skip = ["cp36-*", "cp37-*"]

before-build = [
    "pip install numpy",
    "pip install cython",
    "python setup.py prepare",
    "python setup.py build_ext --inplace",
    "cd ../"
]

# Specify the Python versions and platforms you want to build for
# For example, to build for manylinux, macOS, and Windows:
windows = ["cp38", "cp39", "cp310"]
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
macos = ["cp38", "cp39", "cp310"]


# Run tests after building the wheel
test-command = "pytest {project}/tests"

[[tool.cibuildwheel.overrides]]
select = "cp3{8,9}-*"
manylinux-x86_64-image = "manylinux2010"