[build-system]
requires = ["setuptools","numpy","cython","pyyaml"]
build-backend = "setuptools.build_meta"

[project]
name = "optv"
version = "0.3.0"
description = "OpenPTV "
authors = [
    { name="Alex Liberzon", email="alex.liberzon@gmail.command"}
]
dependencies = [
    "numpy",
    "cython"
]
