[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "packaging==20.5; platform_machine=='arm64'",  # macos M1
    "setuptools==59.2.0",
    "wheel==0.37.0",
    "Cython",  # Note: keep in sync with tools/cythonize.py
    "numpy",
]

[tool.cibuildwheel]
before-build = "pip install numpy cython && cd py_bind && python setup.py prepare"
test-requires = ["nose","six"]
test-command = "cd {project}/py_bind/test && nosetests"
skip = ["cp310-*","pp*"]
