[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "optv"
version = "0.3.0"
description = "OpenPTV "
authors = [
    { name="Alex Liberzon", email="alex.liberzon@gmail.command"}
]
dependencies = [
    "numpy",
    "cython"
]

[tool.cibuildwheel]
before-build = "pip install numpy cython && cd py_bind && python setup.py prepare"
